### ISSUE TITLE
Not a Stitcher Premium subscriber problem

### ISSUE THREAD

**Issue by davehealy** [fancysoups/unofficial-rss#1]
Is there any fix for this error?

"Looks like you're not a Stitcher Premium subscriber. You can subscribe at https://www.stitcher.com/premium"

I am a premium subscriber.

**Comment by shahruz** [comment]
@davehealy This was related to the major Stitcher update that happened earlier this year, it caused accounts to not sync up properly. A new version with a fix is up now at https://v2.unofficialrss.com.
